services:
  - type: web
    name: telegram-bot
    env: python
    pythonVersion: "3.10.0"
    buildCommand: pip install -r requirements.txt
    startCommand: python бот.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
